### ISSUE TITLE
Failed to program

### ISSUE THREAD

**Issue by gksrb4** [NordicSemiconductor/pc-nrfconnect-programmer#155] opened 2019-11-15 04:41 UTC
Product: nRF51822
update V2.6.0 to V3.2.0 , V3.3.0
programmer doesn't work. but It work in nRF52840 product.
I deleted recent version and install V2.6.0 and old programmer. It perfectly work.
Will this be fixed in the next version?

![image](https://user-images.githubusercontent.com/49257699/68917476-c68baa80-07ad-11ea-9847-f8a994afe080.png)

here is log.
13:34:19.258	Segger speed: 2000 kHz
13:34:19.258	Segger version: J-Link V10 compiled Oct 22 2019 16:28:15
13:34:19.259	Core probed: 600108366.
13:34:19.259	Core RAM: 32KiB.
13:34:19.259	Core ROM: 256KiB in pages of 1KiB.
13:34:19.363	Model: NRF51xxx_xxAC_REV3.
13:34:19.859	Core0: Reading device non-volatile memory. This may take a few seconds.
13:34:19.871	Core0: UICR has been read. Click read button to read full non-volatile memory.
13:34:19.974	SoftDevice detected, id 0x87 (S130 v2.0.1)
13:34:19.991	Writing procedure starts for core0
13:34:20.940	HighLevel_probe_init
13:34:20.940	. HighLevel_get_connected_probes
13:34:20.940	. . nRFXX_enum_emu_snr
13:34:20.940	. . . Segger_enum_emu_snr
13:34:20.941	. . . . Segger_enum_emu_snr
13:34:20.941	. . . . . Segger_get_num_emus
13:34:20.941	HighLevel_probe_init:	jlink_path parameter is NULL, using default JLINKARM DLL path given with or obtained in NRFJPROG_dll_open() function.
13:34:20.941	
13:34:20.941	HighLevel_probe_init:	Using JLINKARM DLL at "C:\\Program Files (x86)\\SEGGER\\JLink\\JLinkARM.dll".
13:34:20.941	
13:34:20.941	HighLevel_probe_init:	Creating new probe
13:34:20.941	
13:34:20.941	Debug_Probe-600108366_logger_open
13:34:20.941	Debug_Probe-600108366_logger_open:	nRFJProg logger opened to callback at address 0X5C041670
13:34:20.941	HighLevel_probe_init:	Initialize new probe.
13:34:20.941	
13:34:20.941	Debug_Probe-600108366_initialize
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize:	Copying Segger dll to temporary folder to allow a new probe connection.
13:34:20.942	
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize:	Copy "C:\\Program Files (x86)\\SEGGER\\JLink\\JLinkARM.dll"->"C:\\Users\\HGPARK\\AppData\\Local\\Temp\\nrfjprogdll\\highlevel\\debug\\600108366\\jlinkarm\\s4ec.m"
13:34:20.942	
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize:	Using Segger dll at "C:\\Users\\HGPARK\\AppData\\Local\\Temp\\nrfjprogdll\\highlevel\\debug\\600108366\\jlinkarm\\s4ec.m".
13:34:20.942	
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize:	Copied from "C:\\Program Files (x86)\\SEGGER\\JLink\\JLinkARM.dll".
13:34:20.942	
13:34:20.942	. Debug_Probe-600108366_base_debug_probe_initialize:	Copy "C:\\Users\\HGPARK\\AppData\\Local\\Programs\\nrfconnect\\resources\\app.asar.unpacked\\node_modules\\pc-nrfjprog-js\\build\\Release\\jlinkarm_unknown_nrfjprog.dll"->"C:\\Users\\HGPARK\\AppData\\Local\\Temp\\nrfjprogdll\\highlevel\\debug\\600108366\\s4ec.n"
13:34:20.942	

[2019-11-15T04_34_02.945Z-failed-log.txt](https://github.com/NordicSemiconductor/pc-nrfconnect-programmer/files/3849822/2019-11-15T04_34_02.945Z-failed-log.txt)

**Comment by bencefr** [comment] 2019-11-15 07:11
Hi @gksrb4 ,
Thanks for reporting, we are looking into this issue. Would it be possible to share the hex file?

**Comment by gksrb4** [comment] 2019-11-18 00:46
here are hex files.
[nRF51.zip](https://github.com/NordicSemiconductor/pc-nrfconnect-programmer/files/3856373/nRF51.zip)

**Comment by bencefr** [comment] 2019-11-18 09:04
Hi @gksrb4 , thanks for your help, the issue is fixed and already released as v1.3.1.

**Closed by bencefr** 2019-11-18 09:04 UTC

**Comment by gksrb4** [comment] 2019-11-19 00:38
great!
